### PR TITLE
Merge Jogge/xUnit-TeamCity

### PR DESCRIPTION
**Pull request by carlpett**
Despite adding several very nice features, #18 has been hanging around for soon 5 months without a merge (and even winning the "[People's choice award](https://plugins.jetbrains.com/contest/teamcity/)" in the Teamcity Plugin Contest!). 

Since xUnit 2.2 was released recently, one of the major hold-backs for merging is resolved. I've updated the PR with the full release, as well as fixing some of the other aspects I initially waited for.

@Jogge, @robert-j-engdahl - Any comments on the additions?

### CODE REVIEW

**Comment by carlpett** [comment]
Since this hasn't received any feedback, I will merge this.

**Comment by brunomlopes** [comment]
@carlpett will there be a new release now that the PR is merged? I'd like to update a teamcity instance to support xUnit 2.2 and would prefer to avoid compiling it myself. :)
Thanks

**Comment by carlpett** [comment]
@brunomlopes Yes. I had hoped to do a release the past weekend, but didn't manage to finish the things I would like to get into a 1.2. I could build a pre-release with the current master though, if that'd be helpful?

**Comment by brunomlopes** [comment]
@carlpett that would be very helpful, yes :) thanks.

**Comment by carlpett** [comment]
@brunomlopes Sorry it took a while, but I've posted a pre-release now. Please let me know how it goes!

**Pull request merged**
