### PR TITLE
Added support for parallel processes & user specified arguments for xunit.console.exe

### PR DESCRIPTION
**Pull request by Jogge**
# New features
- Support for parallel processing of test assemblies.
  - Number of parallel processes can be configured in the settings of the plugin.
- Support for user specified command line arguments for xunit.console.exe
- Support for xUnit-2.2.0-beta3 (merge from https://github.com/NsdWorkBook/xUnit-TeamCity)

### CODE REVIEW

**Comment by carlpett** [comment]
Hi,
Thanks for the PR! Especially the command line options part has been on the wish list for some time, it will enhance the plugin quite a bit!

Some points from reading the diff:
- I just closed the PR you merged with, because I don't want to ship a beta version of xUnit. Could you remove those commits? I'll gladly accept a PR for including the new version when it is released :)
- I don't understand what the regex does in building the command line? Also, it would be preferable to compile it outside the for-loop, to avoid paying the compilation cost for every assembly.
- The help text for the command line options are only valid for 2.x versions of xUnit, and probably varies a bit between versions there as well? Ideally I think we should present the list for the selected version.

**Comment by robert-j-engdahl** [comment]
Regarding the regular expression: That is for generating the argv for "int main(int argc, char **argv).  In particular it is not enough to split on the space character, as some options may be enclosed in quotes.  So the regex basically just parses strings and quoted strings.  I acknowledge that the .+?\" thing is a bit unconventional.

**Comment by robert-j-engdahl** [comment]
The help text for command line options could perhaps be generated on the fly, if we can execute the xunit.console.exes from the plugin (we should just shown the output of running the command with no options)

**Comment by robert-j-engdahl** [comment]
Regarding the xunit beta version, I think that can be solved but just calling this version of the team city plugin a beta.

**Comment by carlpett** [comment]
@robert-j-engdahl Yes, but some comment string about the regex would be good, I think.

Regarding the help text, I can see several reasons to "hard code it":
- The ui is generated on the TeamCity server, which may not be able to execute xunit.console for several reasons. It can be a Linux host, it may not have .NET installed, or it may not be a build agent (which would be recommended practice to not run both agent and server on the same host as you scale out), in which case the executable is not even deployed on the machine.
- Forking and running the executable every time the build step page is shown seems likely to be very slow
- We know exactly what text is displayed, and can make sure it fits/filter some uneccessary stuff out, etc.

**Comment by robert-j-engdahl** [comment]
You are right, it should just be inlined.

**Comment by carlpett** [comment]
@robert-j-engdahl @JoggeDK A bit confused regarding the authorship here, but could you please update the PR with the above?

**Comment by carlpett** [comment]
Replaced by #20

**Pull request closed without merging**
